version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

volumes:
  redis-data: 